### ISSUE TITLE
electron

### ISSUE THREAD

**Issue by bvoo** [fooooooooooooooo/fc-injector#4]
**Describe the bug**
Electron

**To Reproduce**
1. Open the app

**Expected behavior**
Expected to use an appropriate amount of memory

**Screenshots**
![image](https://user-images.githubusercontent.com/60059541/131240242-fe699a80-f148-4466-9b7a-bee3b58638e6.png)

**Comment by fooooooooooooooo** [comment]
![pepe__sadge](https://user-images.githubusercontent.com/34515228/131240281-a94241c2-e0f6-478f-b2e1-a6b08e20d33a.png)

**Comment by bvoo** [comment]
fixed in #258
